<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net8.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CloudNimble.WebJobs.Extensions.Amazon\CloudNimble.WebJobs.Extensions.Amazon.csproj" />
    <ProjectReference Include="..\CloudNimble.WebJobs.Extensions.Tests.Common\CloudNimble.WebJobs.Extensions.Tests.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.Integration.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="docker-compose.yml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
