<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<DocumentationFile>$(DocumentationFile)\$(AssemblyName).xml</DocumentationFile>
		<UserSecretsId>9f5c6c4a-1234-4567-890a-1234567890ab</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Azure.WebJobs" Version="3.*" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="5.*" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.*" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="8.*" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.*" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.*" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.*" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.*" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.*" />
		<PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="8.*" />
		<PackageReference Include="AWSSDK.SQS" Version="3.*" />
		<PackageReference Include="AWSSDK.SecurityToken" Version="3.*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CloudNimble.WebJobs.Extensions.Amazon\CloudNimble.WebJobs.Extensions.Amazon.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="appsettings.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
